/**
 * Definisi data master control plane (`platform`).
 * Setiap master relevan >= 10 record.
 */

export const LOCALE_SEED = [
  { code: 'id', name: 'Bahasa Indonesia', nativeName: 'Bahasa Indonesia', direction: 'LTR' as const, enabled: true, isDefault: true, numberFormat: 'id-ID', sortOrder: 1 },
  { code: 'en', name: 'English', nativeName: 'English', direction: 'LTR' as const, enabled: true, isDefault: false, fallbackCode: 'id', numberFormat: 'en-US', sortOrder: 2 },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', direction: 'RTL' as const, enabled: true, isDefault: false, fallbackCode: 'en', numberFormat: 'ar-SA', sortOrder: 3 },
  { code: 'zh-CN', name: 'Simplified Chinese', nativeName: '简体中文', direction: 'LTR' as const, enabled: true, isDefault: false, fallbackCode: 'en', numberFormat: 'zh-CN', sortOrder: 4 },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', direction: 'LTR' as const, enabled: false, isDefault: false, fallbackCode: 'id', numberFormat: 'ms-MY', sortOrder: 5 },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', direction: 'LTR' as const, enabled: false, isDefault: false, fallbackCode: 'en', numberFormat: 'th-TH', sortOrder: 6 },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', direction: 'LTR' as const, enabled: false, isDefault: false, fallbackCode: 'en', numberFormat: 'vi-VN', sortOrder: 7 },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', direction: 'LTR' as const, enabled: false, isDefault: false, fallbackCode: 'en', numberFormat: 'ja-JP', sortOrder: 8 },
  { code: 'ko', name: 'Korean', nativeName: '한국어', direction: 'LTR' as const, enabled: false, isDefault: false, fallbackCode: 'en', numberFormat: 'ko-KR', sortOrder: 9 },
  { code: 'fr', name: 'French', nativeName: 'Français', direction: 'LTR' as const, enabled: false, isDefault: false, fallbackCode: 'en', numberFormat: 'fr-FR', sortOrder: 10 },
];

export const MODULE_CATALOG_SEED = [
  { code: 'POS', name: 'Kasir / POS', category: 'CORE' as const, icon: 'shopping-cart', sortOrder: 1 },
  { code: 'SALES', name: 'Penjualan', category: 'OPERATIONS' as const, icon: 'trending-up', sortOrder: 2 },
  { code: 'PRODUCT_PRICING', name: 'Produk dan Harga', category: 'CORE' as const, icon: 'package', sortOrder: 3 },
  { code: 'CRM', name: 'Pelanggan dan CRM', category: 'OPERATIONS' as const, icon: 'users', sortOrder: 4 },
  { code: 'PURCHASING', name: 'Pembelian', category: 'OPERATIONS' as const, icon: 'shopping-bag', sortOrder: 5 },
  { code: 'WAREHOUSE', name: 'Gudang', category: 'OPERATIONS' as const, icon: 'warehouse', sortOrder: 6 },
  { code: 'INVENTORY', name: 'Persediaan', category: 'OPERATIONS' as const, icon: 'boxes', dependsOn: ['WAREHOUSE'], sortOrder: 7 },
  { code: 'MANUFACTURING', name: 'Produksi', category: 'OPERATIONS' as const, icon: 'factory', dependsOn: ['INVENTORY'], sortOrder: 8 },
  { code: 'QUALITY_CONTROL', name: 'Quality Control', category: 'OPERATIONS' as const, icon: 'badge-check', dependsOn: ['INVENTORY'], sortOrder: 9 },
  { code: 'SHIPPING', name: 'Distribusi dan Pengiriman', category: 'OPERATIONS' as const, icon: 'truck', dependsOn: ['INVENTORY'], sortOrder: 10 },
  { code: 'FINANCE', name: 'Keuangan', category: 'FINANCE' as const, icon: 'wallet', sortOrder: 11 },
  { code: 'ACCOUNTING', name: 'Akuntansi', category: 'FINANCE' as const, icon: 'calculator', dependsOn: ['FINANCE'], sortOrder: 12 },
  { code: 'INVESTOR_REVENUE_SHARE', name: 'Investor dan Bagi Hasil', category: 'FINANCE' as const, icon: 'handshake', dependsOn: ['ACCOUNTING'], sortOrder: 13 },
  { code: 'HUMAN_RESOURCES', name: 'Sumber Daya Manusia', category: 'PEOPLE' as const, icon: 'id-card', sortOrder: 14 },
  { code: 'ATTENDANCE', name: 'Kehadiran', category: 'PEOPLE' as const, icon: 'calendar-check', dependsOn: ['HUMAN_RESOURCES'], sortOrder: 15 },
  { code: 'PAYROLL', name: 'Payroll', category: 'PEOPLE' as const, icon: 'banknote', dependsOn: ['HUMAN_RESOURCES', 'ATTENDANCE'], sortOrder: 16 },
  { code: 'ASSET', name: 'Aset dan Pemeliharaan', category: 'OPERATIONS' as const, icon: 'wrench', sortOrder: 17 },
  { code: 'WORKFLOW', name: 'Workflow dan Persetujuan', category: 'PLATFORM' as const, icon: 'git-branch', sortOrder: 18 },
  { code: 'REPORTING_ANALYTICS', name: 'Laporan dan Analitik', category: 'PLATFORM' as const, icon: 'bar-chart-3', sortOrder: 19 },
  { code: 'INTEGRATION_API', name: 'Integrasi dan API', category: 'PLATFORM' as const, icon: 'plug', sortOrder: 20 },
];

export const FEATURE_CATALOG_SEED = [
  { code: 'POS_OFFLINE_MODE', moduleCode: 'POS', name: 'Mode Offline', featureType: 'BOOLEAN' as const, sortOrder: 1 },
  { code: 'POS_MULTI_TERMINAL', moduleCode: 'POS', name: 'Banyak Terminal per Outlet', featureType: 'LIMIT' as const, defaultLimit: 1, unit: 'terminal', sortOrder: 2 },
  { code: 'POS_RECEIPT_PRINT', moduleCode: 'POS', name: 'Cetak Struk', featureType: 'BOOLEAN' as const, sortOrder: 3 },
  { code: 'SALES_QUOTATION', moduleCode: 'SALES', name: 'Penawaran Penjualan', featureType: 'BOOLEAN' as const, sortOrder: 4 },
  { code: 'PRODUCT_VARIANT', moduleCode: 'PRODUCT_PRICING', name: 'Varian Produk', featureType: 'BOOLEAN' as const, sortOrder: 5 },
  { code: 'PRICE_BOOK_MULTI', moduleCode: 'PRODUCT_PRICING', name: 'Banyak Buku Harga', featureType: 'LIMIT' as const, defaultLimit: 1, unit: 'buku', sortOrder: 6 },
  { code: 'CRM_LOYALTY', moduleCode: 'CRM', name: 'Program Loyalitas', featureType: 'BOOLEAN' as const, sortOrder: 7 },
  { code: 'PURCHASING_BACKORDER', moduleCode: 'PURCHASING', name: 'Backorder', featureType: 'BOOLEAN' as const, sortOrder: 8 },
  { code: 'PURCHASING_APPROVAL', moduleCode: 'PURCHASING', name: 'Persetujuan Bertingkat', featureType: 'BOOLEAN' as const, sortOrder: 9 },
  { code: 'INVENTORY_MULTI_WAREHOUSE', moduleCode: 'WAREHOUSE', name: 'Banyak Gudang', featureType: 'LIMIT' as const, defaultLimit: 2, unit: 'gudang', sortOrder: 10 },
  { code: 'INVENTORY_LOT_TRACKING', moduleCode: 'INVENTORY', name: 'Pelacakan Batch/Lot', featureType: 'BOOLEAN' as const, sortOrder: 11 },
  { code: 'INVENTORY_AUTO_REQUEST', moduleCode: 'INVENTORY', name: 'Request Order Otomatis', featureType: 'BOOLEAN' as const, sortOrder: 12 },
  { code: 'ACCOUNTING_MULTI_ENTITY', moduleCode: 'ACCOUNTING', name: 'Banyak Badan Hukum', featureType: 'LIMIT' as const, defaultLimit: 1, unit: 'entitas', sortOrder: 13 },
  { code: 'HR_ATTENDANCE_DEVICE', moduleCode: 'ATTENDANCE', name: 'Integrasi Mesin Absensi', featureType: 'BOOLEAN' as const, sortOrder: 14 },
  { code: 'PAYROLL_BANK_TRANSFER', moduleCode: 'PAYROLL', name: 'Transfer Bank Payroll', featureType: 'BOOLEAN' as const, sortOrder: 15 },
  { code: 'REPORTING_SCHEDULED', moduleCode: 'REPORTING_ANALYTICS', name: 'Laporan Terjadwal', featureType: 'BOOLEAN' as const, sortOrder: 16 },
  { code: 'API_WEBHOOK', moduleCode: 'INTEGRATION_API', name: 'Webhook Keluar', featureType: 'BOOLEAN' as const, sortOrder: 17 },
  { code: 'STORAGE_QUOTA', moduleCode: 'INTEGRATION_API', name: 'Kuota Penyimpanan', featureType: 'QUOTA' as const, defaultLimit: 5, unit: 'GB', sortOrder: 18 },
  { code: 'WORKFLOW_CUSTOM', moduleCode: 'WORKFLOW', name: 'Workflow Kustom', featureType: 'BOOLEAN' as const, sortOrder: 19 },
  { code: 'ASSET_DEPRECIATION', moduleCode: 'ASSET', name: 'Penyusutan Aset', featureType: 'BOOLEAN' as const, sortOrder: 20 },
];

/**
 * Empat paket awal. Nilai ini hanya seed development/default offering dan dapat
 * diubah Platform Super Admin melalui versi paket baru — bukan dengan mengubah source.
 */
export const SUBSCRIPTION_PLAN_SEED = [
  {
    code: 'POS_STARTER',
    name: 'POS Starter',
    description: 'Kasir dasar untuk satu gerai yang baru mulai.',
    unitPrice: 250000,
    isRecommended: false,
    sortOrder: 1,
    modules: [{ code: 'POS', scope: 'DEVICE' as const }],
    features: ['POS_OFFLINE_MODE', 'POS_RECEIPT_PRINT'],
    constraints: [{ type: 'MIN_DEVICES' as const, value: 1 }],
    tiers: [] as Array<{ min: number; max: number | null; unitPrice: number }>,
  },
  {
    code: 'POS_BUSINESS',
    name: 'POS Business',
    description: 'Kasir, keuangan, akuntansi, gudang, dan persediaan.',
    unitPrice: 400000,
    isRecommended: true,
    sortOrder: 2,
    modules: [
      { code: 'POS', scope: 'DEVICE' as const },
      { code: 'FINANCE', scope: 'TENANT_WIDE' as const },
      { code: 'ACCOUNTING', scope: 'TENANT_WIDE' as const },
      { code: 'WAREHOUSE', scope: 'LEGAL_ENTITY' as const },
      { code: 'INVENTORY', scope: 'LEGAL_ENTITY' as const },
      { code: 'PURCHASING', scope: 'TENANT_WIDE' as const },
      { code: 'PRODUCT_PRICING', scope: 'TENANT_WIDE' as const },
    ],
    features: [
      'POS_OFFLINE_MODE',
      'POS_RECEIPT_PRINT',
      'POS_MULTI_TERMINAL',
      'INVENTORY_MULTI_WAREHOUSE',
      'INVENTORY_AUTO_REQUEST',
      'PURCHASING_BACKORDER',
    ],
    constraints: [{ type: 'MIN_DEVICES' as const, value: 1 }],
    tiers: [
      { min: 1, max: 10, unitPrice: 400000 },
      { min: 11, max: 50, unitPrice: 380000 },
      { min: 51, max: null, unitPrice: 360000 },
    ],
  },
  {
    code: 'POS_PROFESSIONAL',
    name: 'POS Professional',
    description: 'Seluruh POS Business ditambah SDM dan kehadiran.',
    unitPrice: 600000,
    isRecommended: false,
    sortOrder: 3,
    modules: [
      { code: 'POS', scope: 'DEVICE' as const },
      { code: 'SALES', scope: 'TENANT_WIDE' as const },
      { code: 'FINANCE', scope: 'TENANT_WIDE' as const },
      { code: 'ACCOUNTING', scope: 'TENANT_WIDE' as const },
      { code: 'WAREHOUSE', scope: 'LEGAL_ENTITY' as const },
      { code: 'INVENTORY', scope: 'LEGAL_ENTITY' as const },
      { code: 'PURCHASING', scope: 'TENANT_WIDE' as const },
      { code: 'PRODUCT_PRICING', scope: 'TENANT_WIDE' as const },
      { code: 'CRM', scope: 'TENANT_WIDE' as const },
      { code: 'HUMAN_RESOURCES', scope: 'TENANT_WIDE' as const },
      { code: 'ATTENDANCE', scope: 'TENANT_WIDE' as const },
      // PAYROLL sengaja TIDAK termasuk — tersedia sebagai add-on.
    ],
    features: [
      'POS_OFFLINE_MODE',
      'POS_RECEIPT_PRINT',
      'POS_MULTI_TERMINAL',
      'INVENTORY_MULTI_WAREHOUSE',
      'INVENTORY_AUTO_REQUEST',
      'INVENTORY_LOT_TRACKING',
      'PURCHASING_BACKORDER',
      'PURCHASING_APPROVAL',
      'CRM_LOYALTY',
      'HR_ATTENDANCE_DEVICE',
    ],
    constraints: [{ type: 'MIN_DEVICES' as const, value: 1 }],
    tiers: [
      { min: 1, max: 10, unitPrice: 600000 },
      { min: 11, max: null, unitPrice: 570000 },
    ],
  },
  {
    code: 'POS_COMPLETE',
    name: 'POS Complete',
    description: 'Seluruh modul yang aktif pada snapshot versi paket ini.',
    unitPrice: 750000,
    isRecommended: false,
    sortOrder: 4,
    /** ALL_MODULES_AT_VERSION — diisi dari seluruh modul aktif saat publikasi. */
    modules: 'ALL_MODULES_AT_VERSION' as const,
    features: 'ALL_FEATURES_AT_VERSION' as const,
    constraints: [{ type: 'MIN_DEVICES' as const, value: 1 }],
    tiers: [
      { min: 1, max: 10, unitPrice: 750000 },
      { min: 11, max: 50, unitPrice: 700000 },
      { min: 51, max: null, unitPrice: 650000 },
    ],
  },
];

export const SUBSCRIPTION_ADDON_SEED = [
  {
    code: 'ADDON_PAYROLL',
    name: 'Add-on Payroll',
    modules: ['PAYROLL'],
    unitPrice: 150000,
    scope: 'TENANT_WIDE' as const,
  },
  {
    code: 'ADDON_MANUFACTURING',
    name: 'Add-on Produksi',
    modules: ['MANUFACTURING', 'QUALITY_CONTROL'],
    unitPrice: 200000,
    scope: 'TENANT_WIDE' as const,
  },
  {
    code: 'ADDON_INVESTOR',
    name: 'Add-on Investor dan Bagi Hasil',
    modules: ['INVESTOR_REVENUE_SHARE'],
    unitPrice: 175000,
    scope: 'TENANT_WIDE' as const,
  },
];

export const PLATFORM_PERMISSION_SEED = [
  'PLATFORM.REGISTRATION.READ',
  'PLATFORM.REGISTRATION.UPDATE',
  'PLATFORM.TENANT.READ',
  'PLATFORM.TENANT.ACTIVATE',
  'PLATFORM.TENANT.SUSPEND',
  'PLATFORM.TENANT.MIGRATE',
  'PLATFORM.TENANT.SUPPORT_READ',
  'PLATFORM.TENANT.SUPPORT_WRITE',
  'PLATFORM.TENANT.SCHEMA_STATUS',
  'PLATFORM.PRICING.READ',
  'PLATFORM.PRICING.MANAGE',
  'PLATFORM.DISCOUNT.READ',
  'PLATFORM.DISCOUNT.MANAGE',
  'PLATFORM.SUBSCRIPTION.READ',
  'PLATFORM.SUBSCRIPTION.MANAGE',
  'PLATFORM.DEVICE.READ',
  'PLATFORM.DEVICE.MANAGE',
  'PLATFORM.INVOICE.READ',
  'PLATFORM.INVOICE.MANAGE',
  'PLATFORM.PAYMENT.READ',
  'PLATFORM.PAYMENT.RECONCILE',
  'PLATFORM.ESMARTLINK.MANAGE',
  'PLATFORM.I18N.MANAGE',
  'PLATFORM.AUDIT.READ',
  'PLATFORM.SECURITY.MANAGE',
  'PLATFORM.CMS.READ',
  'PLATFORM.CMS.MANAGE',
  'PLATFORM.CMS.PUBLISH',
  'PLATFORM.SEED.MANAGE',
  'PLATFORM.MODULE.MANAGE',
];

export const PLATFORM_ROLE_SEED = [
  {
    code: 'PLATFORM_SUPER_ADMIN',
    name: 'Platform Super Admin',
    roleType: 'SUPER_ADMIN' as const,
    description: 'Akses penuh terhadap seluruh control plane.',
    permissions: '*' as const,
    sortOrder: 1,
  },
  {
    code: 'PLATFORM_SUPPORT',
    name: 'Platform Support',
    roleType: 'SUPPORT' as const,
    description: 'Membaca data tenant melalui support session terbatas.',
    permissions: [
      'PLATFORM.REGISTRATION.READ',
      'PLATFORM.TENANT.READ',
      'PLATFORM.TENANT.SUPPORT_READ',
      'PLATFORM.TENANT.SCHEMA_STATUS',
      'PLATFORM.SUBSCRIPTION.READ',
      'PLATFORM.DEVICE.READ',
      'PLATFORM.INVOICE.READ',
      'PLATFORM.PAYMENT.READ',
      'PLATFORM.AUDIT.READ',
    ],
    sortOrder: 2,
  },
  {
    code: 'PLATFORM_BILLING_ADMIN',
    name: 'Platform Billing Admin',
    roleType: 'BILLING' as const,
    description: 'Mengelola harga, paket, diskon, invoice, dan pembayaran.',
    permissions: [
      'PLATFORM.TENANT.READ',
      'PLATFORM.PRICING.READ',
      'PLATFORM.PRICING.MANAGE',
      'PLATFORM.DISCOUNT.READ',
      'PLATFORM.DISCOUNT.MANAGE',
      'PLATFORM.SUBSCRIPTION.READ',
      'PLATFORM.SUBSCRIPTION.MANAGE',
      'PLATFORM.INVOICE.READ',
      'PLATFORM.INVOICE.MANAGE',
      'PLATFORM.PAYMENT.READ',
      'PLATFORM.PAYMENT.RECONCILE',
      'PLATFORM.ESMARTLINK.MANAGE',
      'PLATFORM.MODULE.MANAGE',
    ],
    sortOrder: 3,
  },
  {
    code: 'PLATFORM_AUDITOR',
    name: 'Platform Auditor',
    roleType: 'AUDITOR' as const,
    description: 'Hanya membaca audit dan status tenant.',
    permissions: [
      'PLATFORM.TENANT.READ',
      'PLATFORM.AUDIT.READ',
      'PLATFORM.INVOICE.READ',
      'PLATFORM.PAYMENT.READ',
    ],
    sortOrder: 4,
  },
  {
    code: 'PLATFORM_CONTENT_EDITOR',
    name: 'Platform Content Editor',
    roleType: 'CUSTOM' as const,
    description: 'Mengelola konten website publik dan CMS.',
    permissions: ['PLATFORM.CMS.READ', 'PLATFORM.CMS.MANAGE', 'PLATFORM.CMS.PUBLISH'],
    sortOrder: 5,
  },
];

/** Channel pembayaran Esmartlink (tanpa credential nyata). */
export const PAYMENT_CHANNEL_SEED = [
  { code: 'VA_BCA', name: 'Virtual Account BCA', adminFee: 4000, sortOrder: 1 },
  { code: 'VA_BRI', name: 'Virtual Account BRI', adminFee: 4000, sortOrder: 2 },
  { code: 'VA_BNI', name: 'Virtual Account BNI', adminFee: 4000, sortOrder: 3 },
  { code: 'VA_MANDIRI', name: 'Virtual Account Mandiri', adminFee: 4000, sortOrder: 4 },
  { code: 'VA_CIMB', name: 'Virtual Account CIMB Niaga', adminFee: 4000, sortOrder: 5 },
  { code: 'VA_PERMATA', name: 'Virtual Account Permata', adminFee: 4000, sortOrder: 6 },
  { code: 'VA_BSI', name: 'Virtual Account BSI', adminFee: 4000, sortOrder: 7 },
  { code: 'QRIS', name: 'QRIS', adminFee: 0.7, feeType: 'PERCENT' as const, sortOrder: 8 },
  { code: 'EWALLET_OVO', name: 'OVO', adminFee: 1.5, feeType: 'PERCENT' as const, sortOrder: 9 },
  { code: 'EWALLET_DANA', name: 'DANA', adminFee: 1.5, feeType: 'PERCENT' as const, sortOrder: 10 },
  { code: 'EWALLET_GOPAY', name: 'GoPay', adminFee: 2, feeType: 'PERCENT' as const, sortOrder: 11 },
  { code: 'RETAIL_ALFAMART', name: 'Gerai Alfamart', adminFee: 5000, sortOrder: 12 },
];

/** Pilihan batas waktu pembayaran (dikarakterisasi dari SmartlinkChannelWindow). */
export const PAYMENT_EXPIRY_OPTIONS = [
  { code: 'MIN_15', labelKey: 'payment.expiry.min15', minutes: 15 },
  { code: 'MIN_30', labelKey: 'payment.expiry.min30', minutes: 30 },
  { code: 'HOUR_1', labelKey: 'payment.expiry.hour1', minutes: 60 },
  { code: 'HOUR_3', labelKey: 'payment.expiry.hour3', minutes: 180 },
  { code: 'HOUR_6', labelKey: 'payment.expiry.hour6', minutes: 360 },
  { code: 'HOUR_24', labelKey: 'payment.expiry.hour24', minutes: 1440 },
  { code: 'DAY_3', labelKey: 'payment.expiry.day3', minutes: 4320 },
  { code: 'WEEK_1', labelKey: 'payment.expiry.week1', minutes: 10080 },
  { code: 'MONTH_1', labelKey: 'payment.expiry.month1', minutes: 43200 },
];
