import { Injectable } from '@nestjs/common';
import { TenantConnectionService } from '../../infrastructure/database/tenant-connection.service';
import { AppError, ErrorCodes } from '../../common/errors/app-error';
export const HOSPITALITY_OUTLET_TYPES = ['RESTAURANT','BAR','ROOM_SERVICE','MINIBAR','RETAIL','SPA'] as const;
export const KITCHEN_TRANSITIONS: Record<string,string[]> = { QUEUED:['PREPARING','CANCELLED'], PREPARING:['READY','CANCELLED'], READY:['SERVED'], SERVED:[], CANCELLED:[] };

@Injectable()
export class PosHospitalityService {
  constructor(private readonly db: TenantConnectionService) {}
  linkOutlet(schema:string,input:{outletId:string;propertyId:string;outletType:string;serviceRate?:string}){const s=`"${schema}"`;return this.db.query(schema,`INSERT INTO ${s}.hospitality_pos_outlet(outlet_id,property_id,outlet_type,service_rate)VALUES($1,$2,$3,$4)ON CONFLICT(outlet_id)DO UPDATE SET property_id=EXCLUDED.property_id,outlet_type=EXCLUDED.outlet_type,service_rate=EXCLUDED.service_rate,active=TRUE RETURNING outlet_id::text,property_id::text,outlet_type,service_rate::text`,[input.outletId,input.propertyId,input.outletType,input.serviceRate??'0']).then(r=>r[0]);}
  lookup(schema:string,propertyId:string,query:string){const s=`"${schema}"`;return this.db.query(schema,`SELECT st.id::text AS stay_id,g.id::text AS guest_id,g.full_name,r.code AS room_code,f.id::text AS folio_id,w.id::text AS window_id FROM ${s}.hospitality_guest_stay st JOIN ${s}.hospitality_guest g ON g.id=st.guest_id LEFT JOIN ${s}.hospitality_room r ON r.id=st.room_id LEFT JOIN ${s}.hospitality_folio f ON f.stay_id=st.id AND f.status='OPEN' LEFT JOIN ${s}.hospitality_folio_window w ON w.folio_id=f.id AND w.window_no=1 WHERE st.property_id=$1 AND st.status='IN_HOUSE' AND (g.full_name ILIKE $2 OR r.code ILIKE $2) ORDER BY g.full_name LIMIT 20`,[propertyId,`%${query}%`]);}
  async attach(schema:string,saleId:string,input:{stayId:string;folioId?:string;windowId?:string;orderSource:string;guestCount?:number}){const s=`"${schema}"`;const rows=await this.db.query(schema,`INSERT INTO ${s}.hospitality_pos_sale_context(pos_sale_id,stay_id,folio_id,window_id,order_source,guest_count,room_charge_status)SELECT $1,$2,$3,$4,$5,$6,CASE WHEN $3::uuid IS NULL THEN NULL ELSE 'PENDING' END WHERE EXISTS(SELECT 1 FROM ${s}.pos_sale p JOIN ${s}.hospitality_pos_outlet o ON o.outlet_id=p.outlet_id JOIN ${s}.hospitality_guest_stay st ON st.id=$2 AND st.property_id=o.property_id WHERE p.id=$1) ON CONFLICT(pos_sale_id)DO UPDATE SET stay_id=EXCLUDED.stay_id,folio_id=EXCLUDED.folio_id,window_id=EXCLUDED.window_id,order_source=EXCLUDED.order_source,guest_count=EXCLUDED.guest_count RETURNING pos_sale_id::text,room_charge_status`,[saleId,input.stayId,input.folioId??null,input.windowId??null,input.orderSource,input.guestCount??null]);if(!rows[0])throw AppError.badRequest(ErrorCodes.VALIDATION_FAILED,'Sale, outlet, atau stay tidak berada pada properti yang sama.');return rows[0];}
  async consumeMeal(schema:string,input:{stayId:string;code:string;date:string;quantity:number;posSaleId?:string},key:string|undefined){if(!key)throw AppError.badRequest(ErrorCodes.VALIDATION_FAILED,'Idempotency-Key wajib.');const s=`"${schema}"`;return this.db.transaction(schema,async c=>{const old=await c.query(`SELECT id::text FROM ${s}.hospitality_meal_consumption WHERE idempotency_key=$1`,[key]);if(old.rows[0])return{...old.rows[0],replayed:true};const rows=await c.query(`UPDATE ${s}.hospitality_meal_entitlement SET consumed=consumed+$4,version=version+1 WHERE stay_id=$1 AND entitlement_code=$2 AND valid_date=$3 AND consumed+$4<=quantity RETURNING id::text,quantity,consumed`,[input.stayId,input.code,input.date,input.quantity]);if(!rows.rows[0])throw AppError.conflict(ErrorCodes.CONFLICT,'Entitlement tidak tersedia atau sudah habis.');const used=await c.query(`INSERT INTO ${s}.hospitality_meal_consumption(entitlement_id,quantity,pos_sale_id,idempotency_key)VALUES($1,$2,$3,$4)RETURNING id::text`,[rows.rows[0].id,input.quantity,input.posSaleId??null,key]);return{...rows.rows[0],consumptionId:used.rows[0].id,replayed:false}});}
  async chargeRoom(schema:string,saleId:string,key:string|undefined,actor:string){if(!key)throw AppError.badRequest(ErrorCodes.VALIDATION_FAILED,'Idempotency-Key wajib.');const s=`"${schema}"`;return this.db.transaction(schema,async c=>{const prior=await c.query(`SELECT id::text FROM ${s}.hospitality_folio_transaction WHERE idempotency_key=$1`,[key]);if(prior.rows[0])return{transactionId:prior.rows[0].id,replayed:true};const sale=await c.query<any>(`SELECT p.grand_total::text,p.tax_total::text,p.business_date::text,p.receipt_number,x.folio_id::text,x.window_id::text FROM ${s}.pos_sale p JOIN ${s}.hospitality_pos_sale_context x ON x.pos_sale_id=p.id WHERE p.id=$1 AND p.status='COMPLETED' AND x.folio_id IS NOT NULL AND x.room_charge_status='PENDING' FOR UPDATE OF x`,[saleId]);if(!sale.rows[0])throw AppError.conflict(ErrorCodes.CONFLICT,'POS sale belum selesai atau room charge tidak siap.');const p=sale.rows[0];const tx=await c.query(`INSERT INTO ${s}.hospitality_folio_transaction(folio_id,window_id,business_date,kind,transaction_code,description,amount,signed_total,source_type,source_reference,idempotency_key,posted_by)VALUES($1,$2,$3,'CHARGE','POS_ROOM_CHARGE',$4,$5,$5,'POS',$6,$7,$8)RETURNING id::text`,[p.folio_id,p.window_id,p.business_date,`POS ${p.receipt_number}`,p.grand_total,saleId,key,actor]);await c.query(`UPDATE ${s}.hospitality_pos_sale_context SET room_charge_status='POSTED',folio_transaction_id=$2 WHERE pos_sale_id=$1`,[saleId,tx.rows[0].id]);await c.query(`INSERT INTO ${s}.hospitality_pos_event_outbox(pos_sale_id,event_type,payload,idempotency_key)VALUES($1,'ROOM_CHARGE_POSTED',$2::jsonb,$3)`,[saleId,JSON.stringify({folioTransactionId:tx.rows[0].id}),`event:${key}`]);return{transactionId:tx.rows[0].id,replayed:false}});}
  kitchen(schema:string,saleId:string,status:string){const s=`"${schema}"`;return this.db.query(schema,`INSERT INTO ${s}.hospitality_kitchen_ticket(pos_sale_id,status,started_at,ready_at,served_at)VALUES($1,$2::varchar,CASE WHEN $2::varchar='PREPARING' THEN now() END,CASE WHEN $2::varchar='READY' THEN now() END,CASE WHEN $2::varchar='SERVED' THEN now() END)ON CONFLICT(pos_sale_id)DO UPDATE SET status=EXCLUDED.status,started_at=COALESCE(${s}.hospitality_kitchen_ticket.started_at,EXCLUDED.started_at),ready_at=COALESCE(${s}.hospitality_kitchen_ticket.ready_at,EXCLUDED.ready_at),served_at=COALESCE(${s}.hospitality_kitchen_ticket.served_at,EXCLUDED.served_at)RETURNING id::text,status,sequence_no`,[saleId,status]).then(r=>r[0]);}
}
