import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { api } from '../../../lib/api';
import { DataGrid,PageHeader,StatusBadge,useToast,type GridColumn } from '../../../components/ui';
import { useErrorMessage } from '../../../app/auth-context';
interface Property{id:string;code:string;nama:string}
interface RoomRow extends Record<string,unknown>{room_id:string;nomor_kamar:string;lantai:string|null;room_type:string;room_condition:string;dnd:boolean;frontdesk_status:string|null;guest_name:string|null;task_id:string|null;task_kind:string|null;task_status:string|null;priority:string|null;workload_points:number|null}

export function HospitalityHousekeepingPage(){
 const toast=useToast(),message=useErrorMessage(),qc=useQueryClient();
 const [propertyId,setPropertyId]=useState(''),[selected,setSelected]=useState<RoomRow|null>(null);
 const [task,setTask]=useState({taskKind:'CHECKOUT',priority:'NORMAL',assignedTo:'',dueAt:''});
 const [note,setNote]=useState(''),[linen,setLinen]=useState({itemCode:'SHEET',movement:'DIRTY',quantity:'1',fromLocation:'ROOM',toLocation:'LAUNDRY'});
 const [lost,setLost]=useState({category:'OTHER',description:'',foundLocation:'',secureStorage:''});
 const props=useQuery({queryKey:['hk-properties'],queryFn:()=>api.get<Property[]>('/hospitality/properti')});
 const board=useQuery({queryKey:['hk-board',propertyId],queryFn:()=>api.get<RoomRow[]>(`/hospitality/housekeeping/board?propertyId=${encodeURIComponent(propertyId)}`),enabled:!!propertyId});
 const refresh=()=>void qc.invalidateQueries({queryKey:['hk-board']});
 const fail=(e:unknown)=>toast.push(message(e,(_k,f)=>f??'Operasi housekeeping gagal.'),'error');
 const create=useMutation({mutationFn:()=>api.post('/hospitality/housekeeping/tasks',{propertyId,roomId:selected!.room_id,taskKind:task.taskKind,priority:task.priority,assignedTo:task.assignedTo||undefined,dueAt:task.dueAt||undefined,checklist:[]},{headers:{'Idempotency-Key':crypto.randomUUID()}}),onSuccess:()=>{toast.push('Tugas berhasil dibuat.','success');refresh();},onError:fail});
 const event=useMutation({mutationFn:(action:string)=>api.post(`/hospitality/housekeeping/tasks/${selected!.task_id}/event`,{action,clientOperationId:crypto.randomUUID(),occurredAt:new Date().toISOString(),note:note||undefined,checklistResult:[]}),onSuccess:()=>{toast.push('Aktivitas mobile tersinkron idempoten.','success');refresh();},onError:fail});
 const flags=useMutation({mutationFn:(dnd:boolean)=>api.post(`/hospitality/housekeeping/rooms/${selected!.room_id}/flags`,{propertyId,dnd,serviceRefused:false,discrepancyNote:note||undefined}),onSuccess:refresh,onError:fail});
 const saveLinen=useMutation({mutationFn:()=>api.post('/hospitality/housekeeping/linen',{propertyId,itemCode:linen.itemCode,movement:linen.movement,quantity:Number(linen.quantity),fromLocation:linen.fromLocation,toLocation:linen.toLocation,occurredAt:new Date().toISOString(),clientOperationId:crypto.randomUUID()}),onSuccess:()=>toast.push('Pergerakan linen tercatat.','success'),onError:fail});
 const saveLost=useMutation({mutationFn:()=>api.post('/hospitality/housekeeping/lost-found',{propertyId,roomId:selected?.room_id,category:lost.category,description:lost.description,foundLocation:lost.foundLocation,foundAt:new Date().toISOString(),secureStorage:lost.secureStorage,clientOperationId:crypto.randomUUID(),photos:[]}),onSuccess:()=>{toast.push('Barang masuk custody chain.','success');setLost({...lost,description:''});},onError:fail});
 const cols:Array<GridColumn<RoomRow>>=[{key:'nomor_kamar',header:'Kamar'},{key:'room_type',header:'Tipe'},{key:'room_condition',header:'Kondisi',render:r=><StatusBadge status={r.room_condition}/>},{key:'frontdesk_status',header:'Front Office',render:r=>r.frontdesk_status?<StatusBadge status={r.frontdesk_status}/>:<span>Vacant</span>},{key:'guest_name',header:'Tamu',render:r=>r.guest_name??'—'},{key:'task_status',header:'Tugas',render:r=>r.task_status?<StatusBadge status={r.task_status}/>:<span>Belum ada</span>},{key:'x',header:'',render:r=><button type="button" className="btn-outline" onClick={()=>setSelected(r)}>Kelola</button>}];
 return <><PageHeader title="Housekeeping" description="Supervisor board dan mobile-safe task, inspeksi, linen, minibar, serta lost-and-found." breadcrumbs={[{label:'Beranda',href:'/app'},{label:'Hospitality'},{label:'Housekeeping'}]}/>
 <section className="card mb-4 p-4"><label><span className="field-label">Properti</span><select className="field-input max-w-md" value={propertyId} onChange={e=>{setPropertyId(e.target.value);setSelected(null);}}><option value="">— Pilih properti —</option>{(props.data??[]).map(p=><option key={p.id} value={p.id}>{p.code} — {p.nama}</option>)}</select></label></section>
 <DataGrid columns={cols} rows={board.data??[]} rowKey={r=>r.room_id} loading={board.isLoading} error={board.isError?'Gagal memuat board.':undefined} onRetry={()=>void board.refetch()} emptyTitle={propertyId?'Belum ada kamar.':'Pilih properti.'}/>
 {selected&&<section className="card mt-4 p-5"><h2 className="text-lg font-semibold">Kamar {selected.nomor_kamar}</h2><label className="mt-3 block"><span className="field-label">Catatan/discrepancy</span><input className="field-input" value={note} onChange={e=>setNote(e.target.value)}/></label>
 {!selected.task_id?<div className="mt-3 grid gap-3 md:grid-cols-4"><select className="field-input" value={task.taskKind} onChange={e=>setTask({...task,taskKind:e.target.value})}><option>CHECKOUT</option><option>STAYOVER</option><option>TURNDOWN</option><option>DEEP_CLEAN</option></select><select className="field-input" value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select><input className="field-input" placeholder="ID petugas" value={task.assignedTo} onChange={e=>setTask({...task,assignedTo:e.target.value})}/><button className="btn-primary" type="button" onClick={()=>create.mutate()}>Buat & assign</button></div>:
 <div className="mt-3 flex flex-wrap gap-2">{selected.task_status==='ASSIGNED'&&<button className="btn-primary" onClick={()=>event.mutate('START')}>Mulai</button>}{selected.task_status==='IN_PROGRESS'&&<><button className="btn-outline" onClick={()=>event.mutate('PAUSE')}>Jeda</button><button className="btn-primary" onClick={()=>event.mutate('COMPLETE')}>Selesai</button></>}{selected.task_status==='PAUSED'&&<button className="btn-primary" onClick={()=>event.mutate('START')}>Lanjut</button>}{selected.task_status==='COMPLETED'&&<button className="btn-primary" onClick={()=>event.mutate('REQUEST_INSPECTION')}>Minta inspeksi</button>}{selected.task_status==='INSPECTION_REQUIRED'&&<><button className="btn-primary" onClick={()=>event.mutate('INSPECT_PASS')}>Inspeksi lulus</button><button className="btn-outline" onClick={()=>event.mutate('INSPECT_FAIL')}>Rework</button></>}<button className="btn-outline" onClick={()=>flags.mutate(!selected.dnd)}>{selected.dnd?'Buka DND':'Set DND'}</button></div>}
 </section>}
 {propertyId&&<div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="card p-5"><h2 className="font-semibold">Linen & Laundry</h2><div className="mt-3 grid gap-2 md:grid-cols-2"><input className="field-input" value={linen.itemCode} onChange={e=>setLinen({...linen,itemCode:e.target.value})}/><select className="field-input" value={linen.movement} onChange={e=>setLinen({...linen,movement:e.target.value})}>{['ISSUE','RETURN','DIRTY','CLEAN','DAMAGED','MISSING','VENDOR_OUT','VENDOR_IN','WRITE_OFF'].map(x=><option key={x}>{x}</option>)}</select><input className="field-input" type="number" min="0.001" value={linen.quantity} onChange={e=>setLinen({...linen,quantity:e.target.value})}/><button className="btn-primary" onClick={()=>saveLinen.mutate()}>Catat movement</button></div></section>
 <section className="card p-5"><h2 className="font-semibold">Lost & Found</h2><div className="mt-3 grid gap-2"><input className="field-input" placeholder="Deskripsi" value={lost.description} onChange={e=>setLost({...lost,description:e.target.value})}/><input className="field-input" placeholder="Lokasi ditemukan" value={lost.foundLocation} onChange={e=>setLost({...lost,foundLocation:e.target.value})}/><input className="field-input" placeholder="Penyimpanan aman" value={lost.secureStorage} onChange={e=>setLost({...lost,secureStorage:e.target.value})}/><button className="btn-primary" disabled={!lost.description||!lost.foundLocation||!lost.secureStorage} onClick={()=>saveLost.mutate()}>Masukkan custody</button></div></section></div>}
 </>;
}
