-- MI-20 configurable long-stay/kos/rental and owner management.
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_rental_contract(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,guest_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_guest(id) ON DELETE RESTRICT,room_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_room(id) ON DELETE RESTRICT,occupant_term VARCHAR(24) NOT NULL DEFAULT 'RESIDENT',unit_term VARCHAR(24) NOT NULL DEFAULT 'UNIT',start_date DATE NOT NULL,end_date DATE,rent_amount NUMERIC(16,2) NOT NULL,billing_day INTEGER NOT NULL,deposit_amount NUMERIC(16,2) NOT NULL DEFAULT 0,status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',renewal_of_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_rental_contract(id) ON DELETE RESTRICT,created_by UUID,CONSTRAINT ck_hospitality_rental_status CHECK(status IN('DRAFT','ACTIVE','NOTICE','TERMINATED','EXPIRED')),CONSTRAINT ck_hospitality_rental_billing_day CHECK(billing_day BETWEEN 1 AND 28));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_move_inspection(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),contract_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_rental_contract(id) ON DELETE RESTRICT,inspection_type VARCHAR(8) NOT NULL,condition JSONB NOT NULL,photos JSONB NOT NULL DEFAULT '[]'::jsonb,signed_by_resident BOOLEAN NOT NULL DEFAULT FALSE,performed_by UUID,performed_at TIMESTAMPTZ NOT NULL DEFAULT now(),CONSTRAINT ck_hospitality_move_inspection_type CHECK(inspection_type IN('MOVE_IN','MOVE_OUT')),UNIQUE(contract_id,inspection_type));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_recurring_charge(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),contract_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_rental_contract(id) ON DELETE RESTRICT,charge_type VARCHAR(20) NOT NULL,period_start DATE NOT NULL,period_end DATE NOT NULL,amount NUMERIC(16,2) NOT NULL,due_date DATE NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'DUE',folio_transaction_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_folio_transaction(id) ON DELETE RESTRICT,idempotency_key VARCHAR(128) NOT NULL UNIQUE,CONSTRAINT ck_hospitality_recurring_status CHECK(status IN('DUE','POSTED','PAID','WAIVED')));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_utility_meter(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),contract_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_rental_contract(id) ON DELETE RESTRICT,meter_type VARCHAR(16) NOT NULL,meter_code VARCHAR(64) NOT NULL,unit_rate NUMERIC(16,4) NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE(contract_id,meter_code));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_utility_reading(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),meter_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_utility_meter(id) ON DELETE RESTRICT,reading_date DATE NOT NULL,value NUMERIC(16,4) NOT NULL,previous_value NUMERIC(16,4),charge_amount NUMERIC(16,2),recorded_by UUID,UNIQUE(meter_id,reading_date),CONSTRAINT ck_hospitality_utility_monotonic CHECK(previous_value IS NULL OR value>=previous_value));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_owner_contract(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,room_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_room(id) ON DELETE RESTRICT,owner_name VARCHAR(180) NOT NULL,owner_reference UUID,commission_percent NUMERIC(7,4) NOT NULL,valid_from DATE NOT NULL,valid_until DATE,status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE',UNIQUE(room_id,valid_from));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_owner_statement(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),owner_contract_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_owner_contract(id) ON DELETE RESTRICT,period_start DATE NOT NULL,period_end DATE NOT NULL,gross_revenue NUMERIC(16,2) NOT NULL,commission NUMERIC(16,2) NOT NULL,expenses NUMERIC(16,2) NOT NULL,net_payable NUMERIC(16,2) NOT NULL,snapshot JSONB NOT NULL,document_hash CHAR(64) NOT NULL,issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(owner_contract_id,period_start,period_end));
CREATE INDEX IF NOT EXISTS ix_hospitality_rental_collection ON "{{TENANT_SCHEMA}}".hospitality_recurring_charge(status,due_date);
