-- MI-15 Folio/cashiering. Semua nominal NUMERIC; posted rows immutable.
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_folio(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,reservation_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_reservation(id) ON DELETE RESTRICT,stay_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_guest_stay(id) ON DELETE RESTRICT,status VARCHAR(12) NOT NULL DEFAULT 'OPEN',currency CHAR(3) NOT NULL DEFAULT 'IDR',opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),closed_at TIMESTAMPTZ,created_by UUID NOT NULL,version INTEGER NOT NULL DEFAULT 1,CONSTRAINT ck_hospitality_folio_status CHECK(status IN('OPEN','CLOSED','TRANSFERRED')));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_folio_window(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),folio_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_folio(id) ON DELETE RESTRICT,window_no INTEGER NOT NULL,payor_type VARCHAR(12) NOT NULL,payor_reference UUID,label VARCHAR(120),credit_limit NUMERIC(16,2),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CONSTRAINT ck_hospitality_window_payor CHECK(payor_type IN('GUEST','COMPANY','GROUP','AGENT','HOUSE')),UNIQUE(folio_id,window_no));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_folio_routing(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),folio_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_folio(id) ON DELETE RESTRICT,from_window_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_folio_window(id) ON DELETE RESTRICT,to_window_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_folio_window(id) ON DELETE RESTRICT,transaction_code VARCHAR(64),valid_from DATE,valid_until DATE,amount_limit NUMERIC(16,2),percentage NUMERIC(7,4),active BOOLEAN NOT NULL DEFAULT TRUE,created_by UUID NOT NULL,CONSTRAINT ck_hospitality_route_distinct CHECK(from_window_id<>to_window_id));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_cashier_shift(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,cashier_id UUID NOT NULL,register_code VARCHAR(64) NOT NULL,business_date DATE NOT NULL,status VARCHAR(12) NOT NULL DEFAULT 'OPEN',opening_float NUMERIC(16,2) NOT NULL DEFAULT 0,expected_cash NUMERIC(16,2),counted_cash NUMERIC(16,2),variance NUMERIC(16,2),opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),closed_at TIMESTAMPTZ,idempotency_key VARCHAR(128) NOT NULL UNIQUE,CONSTRAINT ck_hospitality_cashier_status CHECK(status IN('OPEN','CLOSED','RECONCILED')));
CREATE UNIQUE INDEX IF NOT EXISTS ux_hospitality_cashier_open ON "{{TENANT_SCHEMA}}".hospitality_cashier_shift(property_id,cashier_id)WHERE status='OPEN';
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_folio_transaction(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),folio_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_folio(id) ON DELETE RESTRICT,window_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_folio_window(id) ON DELETE RESTRICT,cashier_shift_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_cashier_shift(id) ON DELETE RESTRICT,business_date DATE NOT NULL,kind VARCHAR(16) NOT NULL,transaction_code VARCHAR(64) NOT NULL,description TEXT NOT NULL,amount NUMERIC(16,2) NOT NULL,tax_amount NUMERIC(16,2) NOT NULL DEFAULT 0,service_amount NUMERIC(16,2) NOT NULL DEFAULT 0,signed_total NUMERIC(16,2) NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'IDR',payment_method VARCHAR(24),provider_key VARCHAR(64),token_reference VARCHAR(180),source_type VARCHAR(32),source_reference VARCHAR(180),accounting_correlation_id UUID,reverses_transaction_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_folio_transaction(id) ON DELETE RESTRICT,idempotency_key VARCHAR(128) NOT NULL UNIQUE,posted_at TIMESTAMPTZ NOT NULL DEFAULT now(),posted_by UUID NOT NULL,metadata JSONB,CONSTRAINT ck_hospitality_folio_tx_kind CHECK(kind IN('CHARGE','PAYMENT','DEPOSIT','REFUND','ADJUSTMENT','ALLOWANCE','REVERSAL')),CONSTRAINT ck_hospitality_folio_no_card CHECK(token_reference IS NULL OR token_reference !~ '^[0-9]{12,19}$'));
CREATE INDEX IF NOT EXISTS ix_hospitality_folio_tx_balance ON "{{TENANT_SCHEMA}}".hospitality_folio_transaction(folio_id,window_id,business_date);
CREATE OR REPLACE FUNCTION "{{TENANT_SCHEMA}}".prevent_folio_transaction_mutation()RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'Posted folio transaction is immutable; use reversal';END$$;
DROP TRIGGER IF EXISTS trg_hospitality_folio_tx_immutable ON "{{TENANT_SCHEMA}}".hospitality_folio_transaction;
CREATE TRIGGER trg_hospitality_folio_tx_immutable BEFORE UPDATE OR DELETE ON "{{TENANT_SCHEMA}}".hospitality_folio_transaction FOR EACH ROW EXECUTE FUNCTION "{{TENANT_SCHEMA}}".prevent_folio_transaction_mutation();
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_city_ledger_account(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,account_type VARCHAR(12) NOT NULL,party_reference UUID NOT NULL,name VARCHAR(180) NOT NULL,credit_limit NUMERIC(16,2) NOT NULL DEFAULT 0,status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE',payment_terms_days INTEGER NOT NULL DEFAULT 0,created_by UUID,CONSTRAINT ck_hospitality_city_status CHECK(status IN('ACTIVE','ON_HOLD','CLOSED')));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_invoice_snapshot(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),folio_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_folio(id) ON DELETE RESTRICT,invoice_no VARCHAR(64) NOT NULL UNIQUE,snapshot JSONB NOT NULL,total NUMERIC(16,2) NOT NULL,issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),issued_by UUID NOT NULL,document_hash CHAR(64) NOT NULL);

