-- MI-18 Corporate, group, allotment, MICE and banquet operations.
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_business_account(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,account_type VARCHAR(16) NOT NULL,name VARCHAR(180) NOT NULL,tax_number VARCHAR(64),credit_limit NUMERIC(16,2) NOT NULL DEFAULT 0,payment_terms_days INTEGER NOT NULL DEFAULT 0,status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CONSTRAINT ck_hospitality_business_account_type CHECK(account_type IN('COMPANY','TRAVEL_AGENT')),CONSTRAINT ck_hospitality_business_account_status CHECK(status IN('ACTIVE','ON_HOLD','CLOSED')));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_negotiated_rate(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),account_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_business_account(id) ON DELETE RESTRICT,rate_plan_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_rate_plan(id) ON DELETE RESTRICT,room_type_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_room_type(id) ON DELETE RESTRICT,valid_from DATE NOT NULL,valid_until DATE NOT NULL,amount NUMERIC(16,2),discount_percent NUMERIC(7,4),active BOOLEAN NOT NULL DEFAULT TRUE,CONSTRAINT ck_hospitality_negotiated_rate_dates CHECK(valid_until>=valid_from));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_group_block(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,account_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_business_account(id) ON DELETE RESTRICT,code VARCHAR(40) NOT NULL,name VARCHAR(180) NOT NULL,arrival_date DATE NOT NULL,departure_date DATE NOT NULL,cutoff_date DATE,status VARCHAR(16) NOT NULL DEFAULT 'TENTATIVE',master_folio_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_folio(id) ON DELETE RESTRICT,billing_instruction JSONB NOT NULL DEFAULT '{}'::jsonb,created_by UUID,CONSTRAINT ck_hospitality_group_dates CHECK(departure_date>arrival_date),CONSTRAINT ck_hospitality_group_status CHECK(status IN('TENTATIVE','DEFINITE','CANCELLED','COMPLETED')),UNIQUE(property_id,code));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_group_allotment(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),group_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_group_block(id) ON DELETE RESTRICT,room_type_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_room_type(id) ON DELETE RESTRICT,stay_date DATE NOT NULL,quantity INTEGER NOT NULL,picked_up INTEGER NOT NULL DEFAULT 0,rate NUMERIC(16,2) NOT NULL,CONSTRAINT ck_hospitality_allotment_qty CHECK(quantity>=0 AND picked_up>=0 AND picked_up<=quantity),UNIQUE(group_id,room_type_id,stay_date));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_rooming_list(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),group_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_group_block(id) ON DELETE RESTRICT,guest_name VARCHAR(180) NOT NULL,guest_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_guest(id) ON DELETE RESTRICT,room_type_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_room_type(id) ON DELETE RESTRICT,reservation_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_reservation(id) ON DELETE RESTRICT,status VARCHAR(16) NOT NULL DEFAULT 'PENDING',notes TEXT);
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_function_space(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,code VARCHAR(40) NOT NULL,name VARCHAR(160) NOT NULL,capacity INTEGER NOT NULL,setup_options JSONB NOT NULL DEFAULT '[]'::jsonb,active BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE(property_id,code));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_event(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,group_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_group_block(id) ON DELETE RESTRICT,account_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_business_account(id) ON DELETE RESTRICT,name VARCHAR(180) NOT NULL,event_type VARCHAR(32) NOT NULL,start_at TIMESTAMPTZ NOT NULL,end_at TIMESTAMPTZ NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'TENTATIVE',expected_guests INTEGER NOT NULL DEFAULT 1,estimated_revenue NUMERIC(16,2) NOT NULL DEFAULT 0,CONSTRAINT ck_hospitality_event_time CHECK(end_at>start_at),CONSTRAINT ck_hospitality_event_status CHECK(status IN('TENTATIVE','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED')));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_event_space(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),event_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_event(id) ON DELETE RESTRICT,function_space_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_function_space(id) ON DELETE RESTRICT,start_at TIMESTAMPTZ NOT NULL,end_at TIMESTAMPTZ NOT NULL,setup_code VARCHAR(40),UNIQUE(function_space_id,start_at,end_at));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_beo(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),event_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_event(id) ON DELETE RESTRICT,version INTEGER NOT NULL,menu JSONB NOT NULL DEFAULT '[]'::jsonb,setup JSONB NOT NULL DEFAULT '{}'::jsonb,timeline JSONB NOT NULL DEFAULT '[]'::jsonb,billing_instruction JSONB NOT NULL DEFAULT '{}'::jsonb,status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',approved_by UUID,approved_at TIMESTAMPTZ,UNIQUE(event_id,version));
CREATE INDEX IF NOT EXISTS ix_hospitality_event_calendar ON "{{TENANT_SCHEMA}}".hospitality_event(property_id,start_at,end_at,status);
