-- MI-23 reporting, evidence-bound AI drafts, help, demo scenarios and observability.
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_report_run(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,report_code VARCHAR(64) NOT NULL,parameters JSONB NOT NULL,result JSONB NOT NULL,document_hash CHAR(64) NOT NULL,generated_by UUID NOT NULL,generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),expires_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_ai_draft(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,use_case VARCHAR(48) NOT NULL,prompt TEXT NOT NULL,evidence JSONB NOT NULL,draft TEXT NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',model_reference VARCHAR(80),created_by UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),approved_by UUID,approved_at TIMESTAMPTZ,CONSTRAINT ck_hospitality_ai_status CHECK(status IN('DRAFT','APPROVED','REJECTED')));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_help_content(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),content_code VARCHAR(80) NOT NULL UNIQUE,title VARCHAR(180) NOT NULL,body TEXT NOT NULL,flowchart JSONB,route VARCHAR(180),role_codes JSONB NOT NULL DEFAULT '[]'::jsonb,active BOOLEAN NOT NULL DEFAULT TRUE,version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_demo_batch(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID NOT NULL REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,scenario_code VARCHAR(64) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',created_by UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),reset_at TIMESTAMPTZ,UNIQUE(property_id,scenario_code,status));
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_notification_outbox(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,channel VARCHAR(16) NOT NULL,recipient_reference VARCHAR(180) NOT NULL,template_code VARCHAR(64),payload JSONB NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'PENDING',attempts INTEGER NOT NULL DEFAULT 0,idempotency_key VARCHAR(128) NOT NULL UNIQUE,next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "{{TENANT_SCHEMA}}".hospitality_observability_event(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),property_id UUID REFERENCES "{{TENANT_SCHEMA}}".hospitality_property(id) ON DELETE RESTRICT,severity VARCHAR(12) NOT NULL,category VARCHAR(32) NOT NULL,message TEXT NOT NULL,metrics JSONB NOT NULL DEFAULT '{}'::jsonb,correlation_id UUID,acknowledged_by UUID,acknowledged_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ix_hospitality_observability_open ON "{{TENANT_SCHEMA}}".hospitality_observability_event(severity,created_at)WHERE acknowledged_at IS NULL;
CREATE OR REPLACE VIEW "{{TENANT_SCHEMA}}".hospitality_maintenance_work_order AS SELECT * FROM "{{TENANT_SCHEMA}}".hospitality_work_order;
CREATE OR REPLACE VIEW "{{TENANT_SCHEMA}}".hospitality_channel_job AS SELECT * FROM "{{TENANT_SCHEMA}}".hospitality_distribution_job;
